var charData = {
    "Hermione (Pure white angel)": "hemin_3",
    "Ping Hai (Delicious Crimson)": "pinghai_6",
    "St. Louis (Luxurious Wheels)": "shengluyisi_4",
    "Jean Bart": "rangbaer_3",
    "Richelieu": "lisailiu_2",
    "Le Malin": "edu_3",
    "Émile Bertin": "aimierbeierding_3",
    "Cooper (Blazing Tennis Battle)": "kubo_2",
    "Z46 (Girls' Relay)": "z46_3",
    "Grozny (Bad Bunny Behind Bars)": "weiyan_2",
    "Aurora (Heritage of Yu City)": "ouruola_4",
    "Taihou (Phoenix's Spring Song)": "dafeng_4",
    "Azuma (Soft Voice of Spring)": "wuqi_2",
    "Yukikaze (Winter's Snowy Wind)": "xuefeng_3",
    "Suruga (Hundred Flowers' Auspice)": "junhe_5",
    "Ryuuhou (Firebird's New Year Dance)": "longfeng_2",
    "Noshiro (Uncharted Festival Grounds?)": "nengdai_2",
    "Ping Hai (Dragon Sisters! [P])": "pinghai_4",
    "Ning Hai (Dragon Sisters! [N])": "ninghai_4",
    "Eldridge (Nyan Nyan Idol?)": "aierdeliqi_5",
    "Admiral Graf Spee (Ironblood ♡ Kawaii)": "sipeibojue_5",
    "Gneisenau (Nightmarish Succubus)": "genaisennao_2", 
    "Surcouf (Shopping Time!)": "xukufu_2", 
    "Shoukaku (Dancing Crane in the Wind)": "xianghe_2", 
    "Zara (Poolside Coincidence)": "zhala_2", 
    "Black Prince (White Princess)": "heitaizi_2",  
    "Vampire (Princess of the Night)": "xixuegui_4",  
    "Honolulu (Festival Date)": "huonululu_5",    
    "Sirius (Midsummer Seirios)": "tianlangxing_3",    
    "Bismarck (Majesty of the Ironblood)": "bisimai_2",
    "Ark Royal (Banquet Guardian)": "huangjiafangzhou_3",    
    "Taihou (Forbidden Feast)": "dafeng_2",
    "Atago (Midsummer March)": "aidang_2",
    "Eldridge (New Year's Handholding)": "aierdeliqi_4",
    "Emile Bertin (Côte d'Azur)": "aimierbeierding_2",
    "Centaur (Undine of the Beach)": "banrenma_2",
    "Belfast (Iridescent Rose)": "beierfasite_2",
    "Javelin": "biaoqiang",
    "Javelin (Beach Picnic!)": "biaoqiang_3",
    "Fubuki (Music Pixy)": "chuixue_3",
    "Deutschland (Service Time?!)": "deyizhi_3",
    "Unicorn (Amusement Park Date)": "dujiaoshou_4",
    "Dunkerque (Summer Sucré)": "dunkeerke_2",
    "Honolulu (Summer Accident?!)": "huonululu_3",
    "Cleveland (Gentry Knight)": "kelifulan_3",
    "Laffey": "lafei",
    "Laffey (New Year Rabbit)": "lafei_4",
    "Ayanami": "lingbo",
    "Akashi": "mingshi",
    "Graf Zeppelin (Beachside Urd)": "qibolin_2",
    "St. Louis (Splendor of Spring)": "shengluyisi_2",
    "St. Louis (Tipsy Snow)": "shengluyisi_3",
    "Tai Yuan (Clamorous Tortoise)": "taiyuan_2",
    "Tirpitz (Snow-melting Summer)": "tierbici_2",
    "Yukikaze": "xuefeng",
    "Ibuki (Wish of a Snow Goddess)": "yichui_2",
    "Z23": "z23",
    "Z46 (First Summer)": "z46_2",
};
